### PR TITLE
Added support for the RP2040 board

### PR DESCRIPTION
**Pull request by abhishekdhamale**
#19

### Command line output
```
PS C:\Users\ELCOME\Documents\RustProjects\rustBoot-Abhishek\rustBoot> cargo rp2040 build-sign-flash rustBoot
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target\debug\xtask.exe rp2040 build-sign-flash rustBoot`
$ cargo build --release
    Finished release [optimized] target(s) in 0.15s
$ cargo build --release
    Finished release [optimized] target(s) in 0.16s
$ cargo build --release
    Finished release [optimized] target(s) in 0.13s
$ py convert2bin.py
$ py signer.py
['sign.py', '--ecc256', '--sha256', 'rp2040_bootfw.bin', 'ecc256.der', '1234']
Update type:          Firmware
Input image:          rp2040_bootfw.bin
Selected cipher:      ecc256
Public key:           ecc256.der
Output image:         rp2040_bootfw_v1234_signed.bin
Not Encrypted
Calculating sha256 digest...
Signing the firmware...
Done.
Output image successfully created.
['sign.py', '--ecc256', '--sha256', 'rp2040_updtfw.bin', 'ecc256.der', '1235']
Update type:          Firmware
Input image:          rp2040_updtfw.bin
Selected cipher:      ecc256
Public key:           ecc256.der
Output image:         rp2040_updtfw_v1235_signed.bin
Not Encrypted
Calculating sha256 digest...
Signing the firmware...
Done.
Output image successfully created.
$ probe-rs-cli download --format Bin --base-address 0x10020000 --chip RP2040 rp2040_bootfw_v1234_signed.bin
     Erasing sectors ✔ [00:00:00] [##############################################################################]  4.00KiB/ 4.00KiB @ 22.56KiB/s (eta 0s )
 Programming pages   ✔ [00:00:00] [##############################################################################]  4.00KiB/ 4.00KiB @ 10.01KiB/s (eta 0s )
    Finished in 0.489s
$ probe-rs-cli download --format Bin --base-address 0x10040000 --chip RP2040 rp2040_updtfw_v1235_signed.bin
     Erasing sectors ✔ [00:00:00] [##############################################################################]  4.00KiB/ 4.00KiB @ 22.96KiB/s (eta 0s )
 Programming pages   ✔ [00:00:00] [##############################################################################]  4.00KiB/ 4.00KiB @  9.73KiB/s (eta 0s )
    Finished in 0.515s
$ cargo flash --chip RP2040 --release
    Finished release [optimized] target(s) in 0.13s
    Flashing C:\Users\ELCOME\Documents\RustProjects\rustBoot-Abhishek\rustBoot\boards\target\thumbv6m-none-eabi\release\rp2040
     Erasing sectors ✔ [00:00:00] [##############################################################################] 48.00KiB/48.00KiB @ 43.30KiB/s (eta 0s )
 Programming pages   ✔ [00:00:02] [##############################################################################] 48.00KiB/48.00KiB @  9.69KiB/s (eta 0s )
    Finished in 3.184s
```

### CODE REVIEW

**Comment by nihalpasham** [comment]
A couple of points:

-  why do we need `rp2040-pac` as a dependency? Isn't `rp2040-hal` enough?
- please add relevant documentation for the `flash-driver`, describing the temporary cache required a data-read and write operation (for ex: during swapping)
-  add documentation that clearly states the need for a custom linker section `.data.ram_func`
- please add self-describing variable names for all variables and use the constants instead of hardcoding integers (ex: 65535)

**Review by yashwanthsinghm — CHANGES_REQUESTED** [review]
1. hal_flash_write() method definition need to be updated ,as per new changes of code. Stating function is run from ram and etc.
2. constants like 0x10000000 ,65536 and 4096 should be stored in constants.
3. variable   x and y should be given meaning full names.
4. Also in for loop instead of 0 to 256 change it to start_page..end_page
5.  In boot_from() function "RedefinedUsize" need to be used instead of direct assigning the value.
       i)        let sp = RefinedUsize::<STACK_LOW, STACK_UP, 0>::bounded_int(
           *(fw_base_address as *const u32)).0;
      ii).       let rv = RefinedUsize::<0, 0, FW_RESET_VTR>::single_valued_int(
           *((fw_base_address + 4) as *const u32)).0
6. In xtask pyocd needs to be changed to probe-rs-cli.
commit these  above changes and resubmit the PR.

**Comment by abhishekdhamale** [comment]
I have pushed it to some PR.

**Comment by yashwanthsinghm** [comment]
I have reviewed changes ,everything looks good now.

**Review by nihalpasham — COMMENTED** [review]
looks good. approved. thank you @abhishekdhamale 🍔

**Comment by nihalpasham** [comment]
looks good. thank you @abhishekdhamale 💥

**Pull request merged**
