### PR TITLE
New board stm32f746zg added.

### PR DESCRIPTION
**Pull request by UdayakumarHidakal**
- #31 added and tested both secure boot and update firmware.

-Command line output
```
udayakumar@udayakumar-VirtualBox:~/devspace/rustBoot$ cargo stm32f746 build rustBoot-only
   Compiling xtask v0.1.0 (/home/udayakumar/devspace/rustBoot/xtask)
    Finished dev [unoptimized + debuginfo] target(s) in 0.46s
     Running `target/debug/xtask stm32f746 build rustBoot-only`
$ cargo build --release
   Compiling version_check v0.9.4
   Compiling typenum v1.15.0
   Compiling proc-macro2 v1.0.40
   Compiling unicode-ident v1.0.1
   ...
   ...
    Finished release [optimized] target(s) in 40.61s
udayakumar@udayakumar-VirtualBox:~/devspace/rustBoot$ cargo stm32f746 build pkgs-for
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/xtask stm32f746 build pkgs-for`
$ cargo build --release
   Compiling stm32f746_bootfw v0.1.0 (/home/udayakumar/devspace/rustBoot/boards/firmware/stm32f746/boot_fw_blinky_green)
    Finished release [optimized] target(s) in 0.93s
$ cargo build --release
   Compiling stm32f746_updtfw v0.1.0 (/home/udayakumar/devspace/rustBoot/boards/firmware/stm32f746/updt_fw_blinky_red)
    Finished release [optimized] target(s) in 0.93s
$ cargo build --release

    Finished release [optimized] target(s) in 0.07s
udayakumar@udayakumar-VirtualBox:~/devspace/rustBoot$ cargo stm32f746 sign pkgs-for
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/xtask stm32f746 sign pkgs-for`
$ python3 convert2bin.py
$ python3 signer.py
['sign.py', '--ecc256', '--sha256', 'stm32f746_updtfw.bin', 'ecc256.der', '1235']
Update type:          Firmware
Input image:          stm32f746_updtfw.bin
Selected cipher:      ecc256
Public key:           ecc256.der
Output image:         stm32f746_updtfw_v1235_signed.bin
Not Encrypted
Calculating sha256 digest...
Signing the firmware...
Done.
Output image successfully created.
['sign.py', '--ecc256', '--sha256', 'stm32f746_bootfw.bin', 'ecc256.der', '1234']
Update type:          Firmware
Input image:          stm32f746_bootfw.bin
Selected cipher:      ecc256
Public key:           ecc256.der
Output image:         stm32f746_bootfw_v1234_signed.bin
Not Encrypted
Calculating sha256 digest...
Signing the firmware...
Done.
Output image successfully created.
udayakumar@udayakumar-VirtualBox:~/devspace/rustBoot$ 


udayakumar@udayakumar-VirtualBox:~/devspace/rustBoot/boards/target/thumbv7em-none-eabihf/release$ probe-run stm32f746 --chip stm32f746zgtx
(HOST) INFO  flashing program (43 pages / 43.00 KiB)
(HOST) INFO  success!
────────────────────────────────────────────────────────────────────────────────
```

### CODE REVIEW

**Review by imrank03 — COMMENTED** [review]
Run cargo format and remove unnecessary spaces.

**Review by imrank03 — CHANGES_REQUESTED** [review]
Add your board in ci.yml file

**Comment by UdayakumarHidakal** [comment]
cargo check done and added stm32f746 board in ci.yml file.

**Review by imrank03 — APPROVED** [review]

**Review by imrank03 — APPROVED** [review]

**Comment by nihalpasham** [comment]
@UdayakumarHidakal  - 🎊 your first PR

**Pull request merged**
