### PR TITLE
Add support for STM32F469 MCU in examples (closes #64)

### LINKED ISSUE #64: Add support for STM32F469 MCU in examples
Hello, and first of all, thanks for this great work.

I have tried to add support for the STM32F469 MCU in the STM HAL.
This chip is used on the [STM32F469-IDISCO board](https://www.st.com/en/evaluation-tools/32f469idiscovery.html) and supporting should be very close to the existing code implemented for STM32F411 and STM32F446.
However, I am wondering how to adjust the value for the constant `FW_RESET_VTR`, for which the definition is based on an offset...
[This offset is 0xA9 in the current STM446 implementation]
(https://github.com/nihalpasham/rustBoot/blob/5a3cc7aa392abeb0ac322aa4279bba5a8eba7c6e/boards/hal/src/stm/stm32f446.rs#L15)
[...and 0x99 in the STM411 implementation](https://github.com/nihalpasham/rustBoot/blob/5a3cc7aa392abeb0ac322aa4279bba5a8eba7c6e/boards/hal/src/stm/stm32f411.rs#L15).

What is the meaning of this offset? How can I adjust this for STM32F469?
In the [STM32 programming manual (PM201)](https://www.st.com/resource/en/programming_manual/pm0214-stm32-cortexm4-mcus-and-mpus-programming-manual-stmicroelectronics.pdf), the vector table is identical regardless of the chip STM32F411 or STM32F446...

### PR DESCRIPTION
**Pull request by lionelains**
This PR allows running rustBoot and its example upgrade flow on the [STM32F469-IDISCO board](https://www.st.com/en/evaluation-tools/32f469idiscovery.html).

On this board, the sample rustBoot flash upgrade process is as follows: (it is executed when issuing `cargo stm32f469 build-sign-flash rustBoot 1234 1235` from the command line)
* Once the demo is flashed on the STM32F469-IDISCO board, press the reset (black button) of the board to start the execution
* The green LED flashes 3 times (while the MCU is running the boot firmware corresponding to source file `boards/firmware/stm32f469/boot_fw_blinky_green/src/main.rs`)
* A delay of a few seconds occurs while the update partition is transferred to the boot partition by rustBoot
* The red LED flashes 3 times (the MCU is now running the update firmware corresponding to source file `boards/firmware/stm32f469/updt_fw_blinky_red/src/main.rs`)
* As soon as the new firmware sets the flash success state, the blue LED turns on while the red LED continues flashing forever

> **Note**  
> When I mention color LEDs above, I mean the front LEDs (next to the LCD screen) of the STM32F469-IDISCO board.

### CODE REVIEW

**Comment by imrank03** [comment]
Acknowledged

**Review by imrank03 — APPROVED** [review]
Thanks @lionelains, looks good and would  you also contribute to the [rustBoot Documentation](https://nihalpasham.github.io/rustBoot-book/index.html)? Add the board to the `Usage` section of the documentation if you are interested.

> @nihalpasham 
> Rust Analyzer seems to fail because the same package and version number is used multiple times, once merged I will create another PR to close #56.

**Review by nihalpasham — APPROVED** [review]
looks good. thanks @lionelains 🎉

**Comment by imrank03** [comment]
Hello @lionelains, sounds good! I am working on that.

**Pull request merged**
