### PR TITLE
Fixed "stm32f4-hal" package issue

### PR DESCRIPTION
**Pull request by imrank03**
Fixed `stm32f4-hal` package issue and tested on hardware.

### CODE REVIEW

**Comment by yashwanthsinghm** [comment]
Acknowledged

**Review by nihalpasham — COMMENTED** [review]
Confirmation: 
1. The `stm32f411` boot-loader in this commit has been tested for 
   - [ ] secure `boot` and 
   - [ ] secure `update` 
   Is that right?
2. If yes, please add relevant (i.e. probe-run) logs for each case. 

Clarifications: 
1. `cortex-m-rt` has been downgraded to version `0.6.14` and `0.6.15` from `0.7.1` - Why?
2. `stm32f4xx-hal` has also been downgraded to version `0.10.1`. I'm assuming the latest version doesn't work or does it have some bug.
3.  I see line 13 in boards/firmware/nrf52840/boot_fw_blinky_green/.cargo/config.toml has been commented out. - Why?

**Review by nihalpasham — APPROVED** [review]
looks good

**Comment by nihalpasham** [comment]
good work @imrank03 💯 

- please add a working copy of (debug) logs to the `stm32f411` bootloader folder (dont forget to edit the lengthy compiler output).

**Pull request merged**
